### ISSUE TITLE
Build Error in flutter 1.12: The method 'AssetSvg.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'. 

### ISSUE THREAD

**Issue by YK-Unit** [YK-Unit/r_dart_library#1]
## Flutter Version Info
```shell
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (2 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

## Build Error
```shell
../../flutter/.pub-cache/git/r_dart_library-0582b4fa70e3350f51d79e64cc096e4396d1a6c5/lib/asset_svg.dart:34:24: Error: The method 'AssetSvg.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(AssetSvg key) {
                       ^
../../flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
```

**Comment by YK-Unit** [comment]
## Solution
I have fixed the build error in 0.2.0 version.

Please add following code to your `pubspec.yaml` for now:

```yaml
dependencies:
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.0
```
